[workspace]
resolver = "3"
members = [
	"crates/cpp",

	"crates/shared",
	"crates/client",
	"crates/server",
	"crates/game-interfaces",

	"crates/sound",
	"crates/utl",
	"crates/interface",
	"crates/convar",
	"crates/math",
	"crates/scratch-pad",
	"crates/tier0",
	"crates/plugin",

	"crates/std",
	"crates/std-macros",
	
	"examples/blank",
	"examples/console",
	"examples/repeated-load",
	"examples/client",
	"examples/filesystem",
	"examples/multithreaded",
	"examples/autoregister",
]

[workspace.package]
authors = ["b0mbie"]

[workspace.dependencies]
printf = { git = "https://github.com/b0mbie/printf-rs.git" }

rse-client = { path = "./crates/client" }
rse-convar = { path = "./crates/convar" }
rse-cpp = { path = "./crates/cpp" }
rse-interface = { path = "./crates/interface" }
rse-shared = { path = "./crates/shared" }
rse-game-interfaces = { path = "./crates/game-interfaces" }
rse-math = { path = "./crates/math" }
rse-plugin = { path = "./crates/plugin" }
rse-scratch-pad = { path = "./crates/scratch-pad" }
rse-server = { path = "./crates/server" }
rse-sound = { path = "./crates/sound" }
rse-std = { path = "./crates/std" }
rse-tier0 = { path = "./crates/tier0" }
rse-utl = { path = "./crates/utl" }

[workspace.dependencies.cppdvt]
git = "https://github.com/b0mbie/cppdvt.git"
version = "0.7.0"

[workspace.dependencies.libc]
version = "0.2.177"
default-features = false

[workspace.dependencies.thiserror]
version = "2.0.16"
default-features = false

[workspace.dependencies.bitflags]
version = "2.10.0"
default-features = false
